### ISSUE TITLE
Embed button no longer working

### ISSUE THREAD

**Issue by mmraby** [okfn/timemapper#200] opened 2017-01-12 16:05 UTC
The embed button is not working: https://discuss.okfn.org/t/embed-button-does-not-work/3419 Any ideas about how to fix this or work around it to embed a timemap on another site?

**Comment by danfowler** [comment] 2017-01-31 23:26
Hi, thanks for flagging.  This is a duplicate of #198 and has been fixed 🎉

**Closed by danfowler** 2017-01-31 23:26 UTC
